<%@ page language="java" contentType="text/html; charset=UTF-8"
pageEncoding="UTF-8" %>
<%@ page import="java.io.*"%>
<%@page import="javax.servlet.*"%>
<%@page import="javax.servlet.ServletOutputStream"%>
 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<%
 
int BUFSIZE = 4096;
String filePath;
{ 
	String filename = request.getParameter("payslipname");
	
	String month=request.getParameter("month");
	String year=request.getParameter("year");
	
	System.out.println("Month is:"+month);
	System.out.println("FileName is:"+filename);
	System.out.println("year is:"+year);
	
	String py="PaySlip";
	
	
	
	filePath="/usr/share/tomcat/webapps/TWPayslips/"+py+"-"+month+"-"+year+"/"+filename+".pdf";
	
	System.out.println("File Path is:"+filePath);
	
	/* 
	String month = request.getParameter("month");
	String year = request.getParameter("year");
	// filePath = "/home/karan/INV/AutogeneratedInvoice"+year+"_"+month+"/"; 
	filePath="/home/c_kapade/VehicleMonthlyInvoices/AutogeneratedInvoice"+year+"_"+month+"/";
	
	

	
filename=filename.replace("^"," ");
System.out.println("After "+filename);
*/

File file = new File(filePath);

System.out.println(filePath);
int length   = 0;
ServletOutputStream outStream = response.getOutputStream();
response.setContentType("text/html");
response.setContentLength((int)file.length());
String fileName = (new File(filePath+"/"+filename)).getName();
response.setHeader("Content-Disposition", "attachment; filename=\"" + fileName+ "\"");
 
byte[] byteBuffer = new byte[BUFSIZE];
DataInputStream in = new DataInputStream(new FileInputStream(file));
 
while ((in != null) && ((length = in.read(byteBuffer)) != -1))
{
outStream.write(byteBuffer,0,length);
}
 
in.close();
outStream.close(); 
}
%>
</body>
</html>