<%@page import="java.io.File"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>List Of Monthly Invoices</title>
<script src="sorttable.js" type="text/javascript"></script>
<link href="css/table.css" rel="stylesheet" type="text/css">
</head>
<body>
<%
System.out.println("reach in List page");
String month=request.getParameter("month");
String year=request.getParameter("year");
System.out.println(year+"  "+month);
String buffer="";
File f = null;
int i=1;
String[] paths;
   try{   
   // f = new File("/home/karan/INV/AutogeneratedInvoice"+year+"_"+month); 
   f = new File("/home/c_kapade/PhysicalDamageInvoices/PHDAutogeneratedInvoice"+year+"_"+month);
   paths = f.list();
   buffer+="<table class='sortable' name='invoiceList'>";
   buffer+="<th>Sr. No.</th><th>Company Name</th><th>File Name</th>";
   for(String file:paths)
   {
	   String []str=file.split("-");
	   
	   
      buffer+="<tr><td>"+i+"</td><td style='text-align: left;'>"+str[0]+"</td><td style='text-align: left;'><a href=Download_21.jsp?year="+year+"&month="+month+"&filename="+file.replace(" ","^")+">"+file+"</td></tr>";
      System.out.println(buffer);
      i++;
   }
   }catch(Exception e){
	   //out.println("No File For This Month");
	   buffer+="<tr><td>No Invoices For This Month</td><tr>";
	   System.out.println(buffer);
   }
buffer+="</table>";
out.println(buffer);
%>
</body>
</html>