
<%@page import="java.util.Date"%>
<%@ include file="conn.jsp"%>


		

	
<%
	Connection con=null ;
	DecimalFormat twoDForm = new DecimalFormat("#.##");
	Statement st=null,st1=null,st2=null,st3=null,st4=null,st5=null;
	String todaysDate=new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
	String todaysTime=new SimpleDateFormat(" HH:mm:ss").format(new java.util.Date());
%>

<%
	
try{	
	Class.forName(DB_Driver);
	con = DriverManager.getConnection(DB_NAME,DB_USERNAME,DB_PASSWORD);
	st=con.createStatement();
	st1=con.createStatement();
	st2=con.createStatement();
	st3=con.createStatement();
	st4=con.createStatement();
	st5=con.createStatement();
	//System.out.println(">>>>>>>>>>>>>>>>>>>>>>>> ??????????????????????????? *********************************************");
	
	String cust=request.getParameter("companyName");
	cust=cust.replace("~~","&");
	System.out.println("%%%%%%%%   $$$$$$$$$$$$   "+cust);
	
	int custocode;
	String sqlCode="SELECT MAX(CustomerCode) from "+session.getAttribute("CompanyMasterID").toString()+"customerdet ";
	ResultSet rs=st.executeQuery(sqlCode);
	rs.next();  
	custocode=rs.getInt(1);
	custocode++;
	System.out.println("AUTOGENERATED CUSTOMER CODE is :   "+custocode);
	
	String sqlData="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"prospectivecustmaster WHERE CompanyName='"+cust+"'";
	ResultSet rsData=st1.executeQuery(sqlData);
	System.out.println("After AUTOGENERATED CUSTOMER CODE Query :   "+sqlData);
	rsData.next();
	String contactperson=rsData.getString("ContactPerson");
	String email=rsData.getString("EMail");
	String website=rsData.getString("WebSite");
	String address=rsData.getString("Address");
	String city=rsData.getString("City");
	String zip=rsData.getString("Zip");
	String state=rsData.getString("State");
	String country=rsData.getString("Country");
	String phone=rsData.getString("Phone");
	String fax=rsData.getString("Fax");
	String interestedproduct=rsData.getString("IntrestedProduct");
	String enteredby=rsData.getString("CustEnteredByRep");
	String weekoff=rsData.getString("WeeklyOffon");
	String addedon=rsData.getString("AddedOnDate");
	String prosaddedon=rsData.getString("ProspCustAddedOn");
	String salescustcode=rsData.getString("SalesCustomerCode");
	String datavalid=rsData.getString("IsDataValid");
	String category=rsData.getString("Category");
	String stdcode=rsData.getString("STDCode");
	String mobile=rsData.getString("MobileNo");
	int resino=rsData.getInt("ResiNo");
	System.out.println(resino);
	String telephone2=rsData.getString("TelephoneNo2");
	String comments=rsData.getString("Comments");
	String potenvalue=rsData.getString("PotentialValue");
	String vendorcode=rsData.getString("VendorCode");
	String assignedby=rsData.getString("Assighnedby");
	String leadref=rsData.getString("leadRef");
	
	// INSERT INTO TABLE2 (COL1, COL2, COL3) SELECT COL1, COL4, COL7 FROM TABLE1
	


	String sqlTransfer="INSERT INTO "+session.getAttribute("CompanyMasterID").toString()+"customerdet ( CustomerCode, CompanyName, ContactPerson,EMail ," 	+
						"WebSite,BillingAddress,BillingCity ,BillingZip ,BillingState ,BillingCountry, "+	
						"BillingPhone ,BillingFax ,ShippingAddress ,ShippingCity ,ShippingZip ,ShippingState, "+
						"ShippingCountry ,ShippingPhone ,ShippingFax ,BankerDetail ,CSTOrMST ,Category, "+	
						"Terms ,CorEForms ,LoginName ,CustPassword ,IntrestedProduct ,TWEmpName ,EnteredOn, "+	
						"IsDataValid ,CustDiscountPercent ,CustCreditLimit ,CustPaymentTerms ,CustPaymentMode,"+ 	
						"STDCode ,MobileNo ,ResiNo ,TelephoneNo2 ,VendorCode ,TallyName ,TransactionExisted)"+
						
						"VALUES('"+custocode+"','"+cust+"' ,'"+contactperson+"' ,'"+email+"', "+
						"'"+website+"' ,'"+address+"' ,'"+city+"' ,'"+zip+"' ,'"+state+"' ,'"+country+"', "+
						"'"+phone+"','"+fax+"' ,'"+address+"' ,'"+city+"','"+zip+"','"+state+"',"+ 
						"'"+country+"' ,'"+phone+"','"+fax+"' ,'-' ,'-','"+category+"',"+ 	
						"'-','-' ,'-' ,'-' ,'"+interestedproduct+"' ,'"+enteredby+"' ,'"+addedon+"',"+ 	
						"'"+datavalid+"' ,'-' ,'0','-','-' , "+
						"'"+stdcode+"','"+mobile+"','"+resino+"','"+telephone2+"','"+vendorcode+"','null','-' )";
						
	System.out.println(sqlTransfer);				
	st2.executeUpdate(sqlTransfer);					
	
	int addresscode=0;
	String sql="SELECT MAX(AddressCode) FROM "+session.getAttribute("CompanyMasterID").toString()+"custaddrdet";
	System.out.println(sql);
	ResultSet rsAdd=st3.executeQuery(sql);
	rsAdd.next();
	addresscode=rsAdd.getInt(1);
	System.out.println(addresscode);
	addresscode++;
	System.out.println("AUTOGENERATED ADDRESS CODE is :" +addresscode);
		 
	String sqlAdd="INSERT INTO "+session.getAttribute("CompanyMasterID").toString()+"custaddrdet (CustomerCode ,AddressCode,IntrestedProduct , ContactPerson , BillingAddress, "+
			"BillingCity ,BillingZip ,BillingState ,BillingCountry ,BillingPhone ,BillingFax ,ShippingAddress ,ShippingCity,"+ 
			"ShippingZip ,ShippingState ,ShippingCountry ,ShippingPhone ,ShippingFax ,EMail ,STDCode ,MobileNo,"+ 	
			"ResiNo ,TelephoneNo2 ,VendorCode)"+
			
			"VALUES( '"+custocode+"' ,'"+addresscode+"' ,'"+interestedproduct+"' ,'"+contactperson+"','"+address+"' ,"+
			"'"+city+"' ,'"+zip+"' ,'"+state+"' ,'"+country+"','"+phone+"','"+fax+"','"+address+"','"+city+"',"+
			"'"+zip+"','"+state+"' ,'"+country+"' ,'"+phone+"' ,'"+fax+"' ,'"+email+"' ,'"+stdcode+"','"+mobile+"',"+
			"'"+resino+"','"+telephone2+"','"+vendorcode+"' ) ";
			
	System.out.println(sqlAdd);
	st4.executeUpdate(sqlAdd);
	
	
	String sqlUpdatePros="UPDATE "+session.getAttribute("CompanyMasterID").toString()+"prospectivecustmaster SET SalesCustomerCode='"+custocode+"' Where CompanyName='"+cust+"'";
	
	st.executeUpdate(sqlUpdatePros);
	
	System.out.println("Update Prospective ---------"+sqlUpdatePros);
	
	
	String sqlUpdatecontactdet="UPDATE "+session.getAttribute("CompanyMasterID").toString()+"contactdet SET SalesCustomerCode='"+custocode+"' Where CompanyName='"+cust+"'";
	
	st.executeUpdate(sqlUpdatecontactdet);
	
	System.out.println("Update ---------contactdet"+sqlUpdatecontactdet);
	
	
	
	response.sendRedirect("alertGoTo.jsp?msg=ProsCustomer Converted To customer and Record Saved Succesfully&goto=home.jsp");
	
	
}	
	catch(Exception e)
{
	System.out.println( "Exception ::"+e );
	response.sendRedirect("home.jsp?msg=!!!! ERROR Inserting Customer.Please try again.");
}
	finally
{
	con.close();
}
%>	

