<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="conn.jsp"%>
<jsp:useBean id="erp" class="com.erp.beans.ERP" scope="page">
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>


	<style type="text/css">
@import url(jscalendar-1.0/calendar-win2k-1.css);
</style>
	<style>
</style>
	<script type="text/javascript" src="jscalendar-1.0/calendar.js"></script>
	<script type="text/javascript" src="jscalendar-1.0/lang/calendar-en.js"></script>
	<script type="text/javascript" src="jscalendar-1.0/calendar-setup.js"></script>

	<script src="sorttable.js" type="text/javascript"></script>

	<script src="dropdown.js" type="text/javascript"></script>
	<script src="ledgerDetails.js" type="text/javascript"></script>


	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Transworld Compressor-Technologies LTD, ERP</title>
	<link href="css/style.css" rel="stylesheet" type="text/css"
		media="screen" />
	<link href="css/table.css" rel="stylesheet" type="text/css"
		media="screen" />
	<style type="text/css">
</style>

	<link rel="stylesheet" type="text/css" href="css/chromestyle2.css" />

	<script type="text/javascript" src="css/chrome.js">
	
</script>
	</head>
	<body>
 



	<%
		erp.getConnection(DB_Driver, DB_NAME, DB_USERNAME, DB_PASSWORD);
	%>
	<%
		Connection conn = null;
			Statement st = null, st1 = null,st2=null,st3=null,st4=null;
			boolean isInvoiceSelected=false;
			String podate="";
			String itemdescription="";
			String transactionId=request.getParameter("transactionId");
			
			if(transactionId.startsWith("SI") || transactionId.startsWith("SP"))
			{
				isInvoiceSelected=true;
			}
			if(transactionId.startsWith("SIC") || transactionId.startsWith("SPC"))
			{
				isInvoiceSelected=false;
			}
			
			try {
				conn = erp.ReturnConnection();
				st = conn.createStatement();
				st2 = conn.createStatement();
				st1 = conn.createStatement();
				st3 = conn.createStatement();
				st4 = conn.createStatement();
			} catch (Exception e) {
			}
	%>

	<div align="center"
		style="font-size: 1.5em; margin-top: 0.4em; margin-bottom: 0.4em; height:4px; background-color: #339CCB">
	</div>


	<div align="center"
		style="font-size: 1.5em;">
		<%if(isInvoiceSelected){ %>
	Invoice : <a><%=request.getParameter("transactionId")%> </a>For <%=request.getParameter("company")%>
	<%} else{%>
	Trasanction : <a><%=request.getParameter("transactionId")%></a> details for <%=request.getParameter("company")%>
	<%}%>
	</a></div>
	 
	<div align="center"
		style="font-size: 1.5em; margin-top: 0.4em; margin-bottom: 1.4em; height:4px; background-color: #339CCB">
	</div>
 

<%
System.out.println("Invoice Selectde :="+isInvoiceSelected);
if(isInvoiceSelected){
	
	double total=0;
	String sqlInvoice="";
	if(transactionId.startsWith("SP") || transactionId.startsWith("SPC"))
	{
		sqlInvoice="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"performainvoicedet WHERE invoiceRefNo='"+transactionId+"'";//performainvoicedet
		
	}
	else{
		 sqlInvoice="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"invoicedet WHERE invoiceRefNo='"+transactionId+"'";
	}
		ResultSet rsInvoice=st.executeQuery(sqlInvoice);
		
		if(rsInvoice.next()){
			try{
				podate=rsInvoice.getString("PODate");
			}catch(Exception e){}
		%>	 
<table  bgcolor="#C6DEFF" width="100%" cellpadding="3" cellspacing="3">
	<tr>
		<td><b>Invoice Date</b></td>
		<td><label><%=new SimpleDateFormat("dd-MMM-yyyy").format(new SimpleDateFormat("yyyy-MM-dd").parse(rsInvoice.getString("InvoiceDate")))+
		"&nbsp;&nbsp; "+rsInvoice.getString("InvoiceTime") %></label></td>
					 	
		<td><b>Customer P.O.Ref</b></td>
		<td><label><%=rsInvoice.getString("PONo") %></label></td>
	</tr>
	<tr>
		<td><b>Sales Enq/Quo Ref</b></td>
		<td><label><%=rsInvoice.getString("SEandSQRefNo") %></label></td>
		<td><b>P.O Date</b></td>
		<td><label><%=podate %></label></td>
	</tr>
	<tr>
		<td><b>Sales Order no</b></td>
		<td><label><%=rsInvoice.getString("TWSalesorderRefNo") %></label></td>
		<td><b>Inv. Generated By</b></td>
		<td><label><%=rsInvoice.getString("TWEmpName") %></label></td>
	</tr>
	<tr>
		<td><b>Contact Person</b></td>
		<td>
		<label><%=rsInvoice.getString("ContactPerson") %></label></td>
		<td><b>Address</b></td>
		<td><label><%=rsInvoice.getString("Address") +  " , "+rsInvoice.getString("City") + " , "+rsInvoice.getString("country") %></label></td>
	</tr>
	<tr>
		<td><b>Phone</b></td>
		<td><label><%=rsInvoice.getString("Phone") %></label></td>
		<td><b>Fax</b></td>
		<td><label><%=rsInvoice.getString("Fax") %></label></td>
	</tr>
</table>
		   
		 
		 <%
		 String sqlItems="";
		 if(transactionId.startsWith("SP"))
			{
			 sqlItems="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"performainvoice_items where InvoiceNo='"+rsInvoice.getString("InvoiceNo")+"'";//performainvoice_items
			}
		 else{
		 sqlItems="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"salesinv_items where InvoiceNo='"+rsInvoice.getString("InvoiceNo")+"'";
		 }
		 System.out.println("Sales Invoice Query---------->"+sqlItems);
		 ResultSet rsItems=st1.executeQuery(sqlItems);
		 %><br>
		 	<div align="center"
		style="font-size: 1.2em; margin-top: 1.0em; margin-bottom: 1em;  ">
		<b>Items included in selected Invoice :</b>  
	</div>
		 <table border="1px"  class="sortable">
 		<tr>
		 	<th>Model</th>
		 	<th>Part No</th>
		 	<th>Desc.</th>
		 	<th>Quantity</th>
		 	<th>Unit Price</th>
		 	<th>Discount %</th>
		 	<th>Tax %</th>
		 	<th>Amount</th>
		</tr>
		 <%
		 while(rsItems.next())
		 {
			 double amount=0.00;
			 String groupName="",refMakeNameTable="",makeName="",tableToBeAccessed="";
			 int groupCode=rsItems.getInt("TheGroup");
			 int makeCode=rsItems.getInt("Make");
		     String itemCode=rsItems.getString("ItemCode");
		     itemdescription=rsItems.getString("itemdescription");
			 String sqlGroup="SELECT TheGroupName from "+session.getAttribute("CompanyMasterID").toString()+"tbl_groupmaster WHERE TheGroupCode='"+groupCode+"'";
		     ResultSet rsGroup=st3.executeQuery(sqlGroup);
		     if(rsGroup.next())
		     	groupName=rsGroup.getString("TheGroupName");
		     if(groupCode<5){
		   	  refMakeNameTable=session.getAttribute("CompanyMasterID").toString()+"tbl_"+groupName.substring(0,5)+"makemaster";
		   	  	
				      String sqlMakename="SELECT MakeName FROM "+refMakeNameTable.toLowerCase()+"  WHERE makecode='"+makeCode+"' ";
				     
				      ResultSet rsMakeName=st4.executeQuery(sqlMakename);
				      if(rsMakeName.next())
				    	  makeName=rsMakeName.getString(1);
				      else
				    	  makeName="-";
				      
				      tableToBeAccessed=session.getAttribute("CompanyMasterID").toString()+"tbl_"+groupName.substring(0,5).toLowerCase()+"im_make"+makeCode+"";
		     }
		     else{
		    	 tableToBeAccessed=""+session.getAttribute("CompanyMasterID").toString()+"tbl_otherim_group"+groupCode;
		   	makeName="-"  ;
		     }
		     
			 String sqlItemDetails="SELECT * FROM "+tableToBeAccessed+"  WHERE ItemCode='"+rsItems.getString("ItemCode")+"' ";
			 System.out.println("Itemcode Details---------->"+sqlItemDetails);
			 ResultSet rsItemDetails=st2.executeQuery(sqlItemDetails);
			 
			 if(rsItemDetails.next())
			 {
				 double tax=0,discount=0;
				 discount=(rsItems.getDouble("DiscountPercent")/100)*(rsItems.getDouble("SellingPrice")*rsItems.getDouble("Quantity"));
				 tax=((rsItems.getDouble("STPercent")/100)*(rsItems.getDouble("SellingPrice")*rsItems.getDouble("Quantity")-discount));
				 
				 System.out.print("st> "+rsItems.getDouble("STPercent")*100);
				 
				 amount=rsItems.getDouble("SellingPrice")*rsItems.getDouble("Quantity")+tax-discount;
				 total+=amount;
				 	 
				 %>
				 <tr>
				 	<td><%=rsItemDetails.getString("Model") %></td>
				 	<td><%=rsItemDetails.getString("Partno") %></td>
				 	<%-- <td><div align="left"><%=rsItemDetails.getString("Description") %></div></td> --%>
				 	<td><div align="left"><%=itemdescription %></div></td>
				 	
				 	<td><div align="right"><%=rsItems.getString("Quantity") %></div></td>
				 	<td><div align="right"><%=rsItems.getString("SellingPrice") %></div></td>
				 	<td><div align="right"><%=rsItems.getString("DiscountPercent") %></div></td>
				 	<td><div align="right"><%=rsItems.getString("STPercent") %></div></td>
				 	<td><div align="right"><%=new DecimalFormat("0.00").format(amount) %></div></td>
				 </tr>
				 
				<%
			 }
		 }
		 %></table><br><div align="right" width="200px;">
<table border="1px"  width="200px" cellpadding="0" cellspacing="0" >
	<tr>
		<th style="background-color: #C6DEFF">Total:</th>
		<td align="right"><label><%=new DecimalFormat("0.00").format(total) %>&nbsp;</label></td>	
		<td rowspan="4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>	 
	</tr>
	<tr>
	<th style="background-color: #C6DEFF">P & FM:</th>
	<td align="right"><label><%=rsInvoice.getString("PFI") %>&nbsp;</label></td>		 
	</tr>
	<tr>
		<th style="background-color: #C6DEFF">Fright:</th>
		<td align="right"><label><%=rsInvoice.getString("FreightAmt") %>&nbsp;</label></td>		 
	</tr>
	<tr><th style="background-color: #C6DEFF">Grand Total:</th>
		<td align="right"><label><%=rsInvoice.getString("GrandTotal") %>&nbsp;</label></td>	 
	</tr>
</table>
</div>
		 
		 			<div align="left"   style="position:absolute;   font-size: 1.1em">
			<b> &nbsp;TERMS & CONDITIONS : </b> &nbsp;&nbsp;*Editable</div>
			
		<div align="left"   style="position:absolute; margin-top: 1em; font-size: 1.1em"> &nbsp;<textarea name="terms" 
	id="search-text" style='width: 450px; height: 150px;'><%=rsInvoice.getString("terms")%></textarea></div>
		 <% 
  }
}else if(transactionId.startsWith("DBN") ||transactionId.startsWith("CRN")|| transactionId.startsWith("SCN") || transactionId.startsWith("SMR") || transactionId.startsWith("SPC") || transactionId.startsWith("SIC") || transactionId.startsWith("BDEBT"))
	{
	System.out.println("IN SCN    SCN   ");
	
	String sqlInvoice1="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"allpaymentdetails WHERE PaymentVoucherNo ='"+transactionId+"'";
	System.out.println(sqlInvoice1);
	ResultSet rsTransaction1=st.executeQuery(sqlInvoice1);
	if(rsTransaction1.next()){%>
<table  bgcolor="#C6DEFF" width="100%" cellpadding="3" cellspacing="3">
<tr>
	<td><b>Payment Mode</b></td>
	<td style="width: 200px;"><label><%=rsTransaction1.getString("PaymentMode") %></label></td>
	<td><b>Payment Date</b></td><td><label><%=rsTransaction1.getString("PaymentDate") %></label></td>
</tr>
<tr>
	<td><b>Amount Paid</b></td>
	<td><label><%=rsTransaction1.getString("AmountPaid") %></label></td>
	<td><b>Ch/DD/CNote No</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDorCreditNoteNo") %></label></td>
</tr>
<tr>
	<td><b>Ch/DD/CNote Date</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDorCreditNoteDate") %></label></td>
	<td><b>Bank Name</b></td>
	<td><label><%=rsTransaction1.getString("BankName") %></label></td>
</tr>			 	
<tr>
	<td><b>Branch Name</b></td>
	<td><label><%=rsTransaction1.getString("BranchName") %></label></td>
	<td><b> City</b></td>
	<td><label><%=rsTransaction1.getString("City") %></label></td>
</tr>
<tr>
	<td><b>Entered By</b></td>
	<td><label><%=rsTransaction1.getString("TWEmpName") %></label></td>
	<td><b> Ch/DD En-cash Status</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDEncashedStatus") %></label></td>
</tr>
<tr>
	<td><b>Ch/DD En-cash Date</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDEncashedOnDate") %></label></td>
	<td><b> Remarks</b></td>
	<td><label><%=rsTransaction1.getString("Remarks") %></label></td>
</tr>
</table>
<div align="center" style="font-size: 1.5em; margin-top: 1.4em; margin-bottom: 0.4em; height:4px; background-color: #339CCB">
</div>
<%}
}else{
	
	String sqlInvoice1="SELECT * FROM "+session.getAttribute("CompanyMasterID").toString()+"allpaymentdetails WHERE ChOrDDorCreditNoteNo ='"+transactionId+"'";
	System.out.println(sqlInvoice1);
	ResultSet rsTransaction1=st.executeQuery(sqlInvoice1);
	if(rsTransaction1.next()){%>
<table  bgcolor="#C6DEFF" width="100%" cellpadding="3" cellspacing="3">
<tr>
	<td><b>Payment Mode</b></td>
	<td style="width: 200px;"><label><%=rsTransaction1.getString("PaymentDetails") %></label></td>
	<td><b>Payment Date</b></td><td><label><%=rsTransaction1.getString("PaymentDate") %></label></td>
</tr>
<tr>
	<td><b>Amount Paid</b></td>
	<td><label><%=rsTransaction1.getString("AmountPaid") %></label></td>
	<td><b>Ch/DD/CNote No</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDorCreditNoteNo") %></label></td>
</tr>
<tr>
	<td><b>Ch/DD/CNote Date</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDorCreditNoteDate") %></label></td>
	<td><b>Bank Name</b></td>
	<td><label><%=rsTransaction1.getString("BankName") %></label></td>
</tr>			 	
<tr>
	<td><b>Branch Name</b></td>
	<td><label><%=rsTransaction1.getString("BranchName") %></label></td>
	<td><b> City</b></td>
	<td><label><%=rsTransaction1.getString("City") %></label></td>
</tr>
<tr>
	<td><b>Entered By</b></td>
	<td><label><%=rsTransaction1.getString("TWEmpName") %></label></td>
	<td><b> Ch/DD En-cash Status</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDEncashedStatus") %></label></td>
</tr>
<tr>
	<td><b>Ch/DD En-cash Date</b></td>
	<td><label><%=rsTransaction1.getString("ChOrDDEncashedOnDate") %></label></td>
	<td><b> Remarks</b></td>
	<td><label><%=rsTransaction1.getString("Remarks") %></label></td>
</tr>
</table>
<div align="center" style="font-size: 1.5em; margin-top: 1.4em; margin-bottom: 0.4em; height:4px; background-color: #339CCB">
</div>
<%}
	
}
	try{
	conn.close();
	}catch(Exception e){}
	%>
<!-- <br><br> <br><br> <br><br> <br><br>
	<br><br> <br><br> <br><br> <br><br>
	<br><br> <br><br> <br><br> <br><br> -->
	<div id="footer">
	<!-- <p><a href="http://www.myfleetview.com"> Copyright &copy; 2009
	by Transworld Compressor Technologies Ltd. All Rights Reserved.</a></p> -->
	
	<%@ include file="footer_new.jsp" %>
	</div>
	<!-- end #footer -->
	</body>
	</html>
</jsp:useBean>