<%@ include file="conn.jsp"%>

<head>
<title>View Payroll Xmls</title>
<script type="text/javascript">
function view(addr){
	window.open("XMLDocument.jsp?documentName="+addr, "View XML","width=850,height=500,toolbar=0,menubar=0,location=0");
	//,"width=800,height=500,toolbar=0,menubar=0,location=0"
}

</script>
</head>
<body>
<%
System.out.println("here");
Connection conn=null;
Class.forName(DB_Driver);
conn=DriverManager.getConnection(DB_NAME,DB_USERNAME,DB_PASSWORD);
System.out.println("1");
Statement st_select=conn.createStatement();
String com=(String)session.getAttribute("CompanyMasterID");
String sql="select * from "+com+"payrollXML";
ResultSet rs_select=st_select.executeQuery(sql);
System.out.println("2");
%>
<br><br><br>
<table style="" align="center" border="1">
<tr>
<th>Generated By</th>
<th>Generated Date</th>
<th>File Name</th>
</tr>

<%
while(rs_select.next()){
	System.out.println(rs_select.getString("generatedby"));
	System.out.println("---"+rs_select.getString("filename"));
	%>
	<tr>
	<td><%=rs_select.getString("generatedby") %></td>
	<td><%=rs_select.getString("entrydatetime") %></td>
	<td><a href="#" onclick="view('<%=rs_select.getString("filename") %>')"> <%=rs_select.getString("filename") %> </a></td>
	</tr>
<%
}
%>
</table>
</body>
</html>