<%@ page language="java" import="java.sql.*" import=" java.text.*" import=" java.util.*" errorPage="" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <%@ include file="header.jsp"%>
<head>
<style type="text/css">@import url(jscalendar-1.0/calendar-win2k-1.css);</style>
	<script type="text/javascript" src="jscalendar-1.0/calendar.js"></script>
	<script type="text/javascript" src="jscalendar-1.0/lang/calendar-en.js"></script>
	<script type="text/javascript" src="jscalendar-1.0/calendar-setup.js"></script>
	<script type="text/javascript" src="js/ajax-dynamic-content.js"></script>
	<script type="text/javascript" src="js/ajax.js"></script>
	<script type="text/javascript" src="js/ajax-tooltip.js"></script>	
	<script src="js/sorttable.js" type="text/javascript"></script>
	<script type="text/javascript" src="scrollabletable.js"></script>
<script>
var thumbnail="";
//var thumbnailn="";
function GetFiles(file,i)
{
	var thumbnailn="";
	if((document.getElementById("cb"+i).checked)==true)
	{
		if(thumbnail=="")
		{
			thumbnail=file;
		}
		else
		{
			thumbnail=thumbnail+","+file;
		}
	}

	if((document.getElementById("cb"+i).checked)==false)
	{
		if(thumbnailn=="")
		{
			thumbnailn=file;
		}
		else
		{
			thumbnailn=thumbnailn+","+file;
		}
	}
	thumbNail(thumbnail,thumbnailn);
}
function reload()
{
	window.location.reload();
}
</script>
</head>

<body>
<%
Connection conn=null;
Class.forName(DB_Driver);
conn=DriverManager.getConnection(DB_NAME,DB_USERNAME,DB_PASSWORD);
		Statement stmt=null,st1=null;
		String sql=null;
		ResultSet rst=null;
		stmt=conn.createStatement();
		st1=conn.createStatement();
		
		DateFormat df123= new SimpleDateFormat("dd-MMM-yyyy");
		DateFormat df1234= new SimpleDateFormat("yyyy-MM-dd");
		String dataDate1="";
		String dataDate2="";
		String fname="";
		int srno=0;
		int sn=1;
%>

<table align="center"> 
<tr><td align="center">
<font size="3" color="#151B54"><b>Generated XML Documents </b></font><br><br>
</td></tr>

</table>
<table style="width: 60%;" align="center" border="1" class='sortable'>
<tr>
<th>Generated By</th>
<th>Generated Date</th>
<th>File Name</th>
</tr>
<%
int trcnt=0;
String com=(String)session.getAttribute("CompanyMasterID");
try
{
	String sqlData="";
	try
	{
		System.out.println(">>>>>>>>>>>>"+request.getQueryString().toString());
		//String sql="select * from t_payrollXML";
		sqlData="select * from "+com+"payrollXML";
	}
	catch(Exception e)
	{
		sqlData="select * from "+com+"payrollXML";
	}
		
	ResultSet rs1=st1.executeQuery(sqlData);
		
	while(rs1.next()){
		%>
		<tr>
		<td><%=rs1.getString("generatedby") %></td>
		<td><%=rs1.getString("entrydatetime") %></td>
		<td><a href="downloadFile.jsp?documentName=<%=rs1.getString("filename")%>"><%=rs1.getString("filename")%></a></td>
		</tr>
	<%
	}
}
catch(Exception e)
{
	System.out.println("Thumbnail Exception======>>"+e);	
}

%>

</table>

</form>
<div id="footer" style="margin-top: 20%">
<p><a href="http://www.myfleetview.com"> Copyright &copy; 2009
by Transworld  Technologies Ltd. All Rights Reserved.</a></p>
</div>
</body>
</html>
